name: After fix (eject)
on: [workflow_dispatch]
jobs:
  after:
    name: After fix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      
      - name: Setup Expo
        uses: expo/expo-github-action@v6
        with:
          expo-version: 4.x
          expo-cache: true
      
      - name: Setup Project
        run: expo init ExpoIssue13475Fix --template expo-template-blank@42
        
      - name: Use faulty version on Windows
        if: github.event.inputs.os == 'windows'
        working-directory: ExpoIssue13475Fix
        run: |
          mv app.json app-old.json
          jq '.expo.android.package = \"com.bycedric.expoissue13475\"' app-old.json > app.json
          
      - name: Use faulty version on MacOS/Ubuntu
        if: github.event.inputs.os != 'windows'
        working-directory: ExpoIssue13475Fix
        run: |
          mv app.json app-old.json
          jq '.expo.android.package = "com.bycedric.expoissue13475"' app-old.json > app.json
        
      - name: Eject Project
        working-directory: ExpoIssue13475Fix
        run: expo eject
      
      - name: Validate good version
        working-directory: ExpoIssue13475Fix
        run: |
          yarn why @unimodules/react-native-adapter
          yarn why expo-modules-autolinking

      - name: Create APK
        working-directory: ExpoIssue13475Fix/android
        run: ./gradlew assembleDebug

      - name: Store APK
        uses: actions/upload-artifact@v2
        with:
          name: app.apk
          path: |
            ExpoIssue13475Fix/android/app/build/outputs/apk/debug/app-debug.apk
