name: Before fix
on:
  workflow_dispatch:
    inputs:
      os:
        description: OS to use (windows/macos/linux)
        required: true
        default: windows
jobs:
  before:
    name: Before fix
    runs-on: ${{ github.event.inputs.os }}-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      
      - name: Setup Expo
        uses: expo/expo-github-action@v6
        with:
          expo-version: 4.x
          expo-cache: true
      
      - name: Setup Project
        run: expo init ExpoIssue13475Error --template expo-template-bare-minimum@42

      - name: Use faulty version
        working-directory: ExpoIssue13475Error
        run: >
          mv package.json package-old.json
          jq '.resolutions = { \"@unimodules/react-native-adapter\": \"6.3.1\" }' package-old.json > package.json

      - name: Reinstall modules
        working-directory: ExpoIssue13475Error
        run: >
          npx rimraf node_modules yarn.lock
          yarn install
      
      - name: Validate faulty version
        working-directory: ExpoIssue13475Error
        run: yarn why @unimodules/react-native-adapter

      - name: Create APK
        working-directory: ExpoIssue13475Error/android
        run: ./gradlew assembleDebug

      - name: Store APK
        uses: actions/upload-artifact@v2
        with:
          name: app.apk
          path: |
            ExpoIssue13475Error/android/app/build/outputs/apk/debug/app-debug.apk
            ExpoIssue13475Error/android/app/build/outputs/apk/debug/outut-metadata.json
